### PR TITLE
Upgrade to babel6.

### PR DESCRIPTION
**Pull request by iamolivinius**
Upgrade babel to version 6. Babel 5 is deprecated and babel-core@5.6.17 isn't available on npm anyway. See error in PR #8

### CODE REVIEW

**Comment by jmdobry** [comment]
Please remove any changes to anything in `dist/` and make sure it's squashed into 1 commit, and I'll merge.

**Comment by iamolivinius** [comment]
`done()` :smile:

**Comment by jmdobry** [comment]
Also, please remove your changes to `*.spec.js`, and again squash into 1 commit.

**Comment by iamolivinius** [comment]
The changes were necessary because the CI failed: https://circleci.com/gh/js-data/js-data-localforage/16

**Comment by jmdobry** [comment]
Don't worry about the CI, I'll figure that out.

**Comment by iamolivinius** [comment]
:+1:

**Pull request merged**
